cloud:
  aws:
    sqs:
      endpoint: http://localhost:4566

management:
  server:
    port: 8081
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - prometheus

contributions:
  sqs: NEW_CONTRIBUTIONS
