global:
  scrape_timeout: 3s
  scrape_interval: 5s

scrape_configs:
  - job_name: analyzer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8081 # Prometheus scrape localhost application.
